services:
  node:
    build:
      context: ./node
      dockerfile: Dockerfile.prod
    image: yulken/desafio_node_node:latest
    container_name: node
    networks:
      - my_network
    depends_on:
      db:
        condition: service_healthy
    volumes: 
    - ./node/:/usr/src/app
    - /usr/src/app/node_modules

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.prod
    image: yulken/desafio_node_nginx:latest
    container_name: nginx
    networks:
      - my_network
    ports:
      - "8080:80"
    depends_on:
      - node
  db:
      image: mysql:5.7
      command: --innodb-use-native-aio=0
      container_name: db
      restart: always
      tty: true
      healthcheck:
        test: /usr/bin/mysql -u root -p$${MYSQL_ROOT_PASSWORD} --execute "SHOW DATABASES;"
        interval: 2s
        timeout: 10s
        retries: 3
      ports:
      - "3306:3306"
      volumes:
        - ./mysql:/var/lib/mysql
        - ./node/migrations/:/docker-entrypoint-initdb.d
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: nodedb
      networks:
        - my_network

networks:
  my_network:
    driver: bridge